export const STORE_METHODS = [
  'open',
  'close',
  'isOpen',
  'reset',
  'hasLayout',
  'inTransaction',
  'transaction',
  'getMeta',
  'setMeta',
  'addEvent',
  'listEvents',
  'insertNode',
  'updateNode',
  'getNode',
  'listNodes',
  'insertLog',
  'listLogs',
  'listRecentLogs',
  'countLogs',
  'deleteLogs',
  'hasReceipt',
  'insertReceipt',
  'getMaster',
  'putMaster',
  'deleteMaster',
  'listMasters',
  'suspendMasters',
  'updateMasterIp',
  'countSuspendedMasters',
  'getBuffer',
  'insertBuffer',
  'updateBuffer',
  'listBuffers',
  'deleteBuffers',
  'suspendBuffers',
  'updateBufferIp',
  'getPending',
  'putPending',
  'listPending',
  'deletePending',
  'suspendPending',
  'updatePendingIp',
  'getMergeJob',
  'insertMergeJob',
  'deleteMergeJob',
  'getFragment',
  'putFragment',
  'deleteFragment',
  'listFragments',
  'countFragments',
  'getIndex',
  'putIndex',
  'deleteIndex',
  'listIndexes',
  'updateIndexIpByAlias',
  'suspendIndexes',
  'listOutbox',
  'insertOutbox',
  'deleteOutbox',
  'countOutbox',
  'getRecord',
  'putRecord',
  'deleteRecord',
  'listRecords',
  'listRecordsByHome',
  'updateRecordHome',
  'deleteRecordHome',
  'latestStamp',
  'clearHolder'
]

export function assertStore(store) {
  const missing = STORE_METHODS.filter((name) => typeof store?.[name] !== 'function')
  if (missing.length === 0) return
  const error = new Error(`存储缺少方法：${missing.join('、')}`)
  error.expose = true
  throw error
}
